eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://47.56.250.140:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: eiz-admin-config
server:
  port: 8088
